"""Test reading HERD from files created with hdmf-common-schema 1.8.0.

In schema 1.8.0, HERD was defined in the hdmf-experimental namespace.
These tests verify that HERD is read correctly and is resolved to the
hdmf-common namespace when using the current schema.
"""

from hdmf.common import get_hdf5io, get_type_map, CORE_NAMESPACE, SimpleMultiContainer
from hdmf.common.resources import HERD
from hdmf.testing import TestCase


class TestHERD_1_8_0(TestCase):
    """Test reading HERD from files written with hdmf-common-schema 1.8.0.

    The test files were generated by make_test_files.py using hdmf 4.3.1
    (hdmf-common-schema 1.8.0) where HERD was in the hdmf-experimental
    namespace. The HDF5 file contains a SimpleMultiContainer with a Data
    object, and the ZIP file contains the HERD tables.
    """

    def setUp(self):
        self.path_h5 = "tests/unit/back_compat_tests/herd_1_8_0.h5"
        self.path_zip = "tests/unit/back_compat_tests/herd_1_8_0.zip"

    def test_read_container(self):
        """Test that the SimpleMultiContainer with data is read correctly."""
        with get_hdf5io(path=self.path_h5, mode="r") as io:
            container = io.read()
            self.assertIsInstance(container, SimpleMultiContainer)
            self.assertIn("species", container.containers)

    def test_read_herd_from_zip(self):
        """Test that HERD written under hdmf-experimental is read correctly from ZIP."""
        herd = HERD.from_zip(path=self.path_zip)
        self.assertIsInstance(herd, HERD)
        self.assertEqual(len(herd.keys.data), 1)
        self.assertEqual(herd.keys.data[0][0], "Homo sapiens")
        self.assertEqual(len(herd.entities.data), 1)
        self.assertEqual(herd.entities.data[0][0], "NCBI_TAXON:9606")

    def test_read_herd_with_hdf5io(self):
        """Test that HERD is loaded when reading HDF5 with herd_path."""
        with get_hdf5io(path=self.path_h5, mode="r", herd_path=self.path_zip) as io:
            io.read()
            self.assertIsInstance(io.herd, HERD)

    def test_herd_namespace_is_common(self):
        """Test that HERD is resolved in the hdmf-common namespace."""
        tm = get_type_map()
        dt = tm.namespace_catalog.get_spec(CORE_NAMESPACE, "HERD")
        self.assertIsNotNone(dt)
