trigger: none

pr: none

schedules:
- cron: "0 5 * * *"
  displayName: nightly
  branches:
    include: dev

jobs:

- job: 'Test'
  displayName: "Test HDMF"

  strategy:
    matrix:
      macOS-py3.10:
        imageName: 'macos-10.15'
        pythonVersion: '3.10'
        testToxEnv: 'py310'
        buildToxEnv: 'build-py310'

      macOS-py3.10-upgrade-dev-pre:
        imageName: 'macos-10.15'
        pythonVersion: '3.10'
        testToxEnv: 'py310-upgrade-dev-pre'
        buildToxEnv: 'build-py310-upgrade-dev-pre'

      macOS-py3.10-upgrade-dev:
        imageName: 'macos-10.15'
        pythonVersion: '3.10'
        testToxEnv: 'py310-upgrade-dev'
        buildToxEnv: 'build-py310-upgrade-dev'

      macOS-py3.10-opt:
        imageName: 'macos-10.15'
        pythonVersion: '3.10'
        testToxEnv: 'py310-opt'
        buildToxEnv: 'build-py310-opt'

      macOS-py3.9:
        imageName: 'macos-10.15'
        pythonVersion: '3.9'
        testToxEnv: 'py39'
        buildToxEnv: 'build-py39'

      macOS-py3.8:
        imageName: 'macos-10.15'
        pythonVersion: '3.8'
        testToxEnv: 'py38'
        buildToxEnv: 'build-py38'

      macOS-py3.7:
        imageName: 'macos-10.15'
        pythonVersion: '3.7'
        testToxEnv: 'py37'
        buildToxEnv: 'build-py37'

      macOS-py3.7-min-req:
        imageName: 'macos-10.15'
        pythonVersion: '3.7'
        testToxEnv: 'py37-min-req'
        buildToxEnv: 'build-py37-min-req'

      Windows-py3.10:
        imageName: 'vs2017-win2016'
        pythonVersion: '3.10'
        testToxEnv: 'py310'
        buildToxEnv: 'build-py310'

      Windows-py3.10-upgrade-dev-pre:
        imageName: 'vs2017-win2016'
        pythonVersion: '3.10'
        testToxEnv: 'py310-upgrade-dev-pre'
        buildToxEnv: 'build-py310-upgrade-dev-pre'

      Windows-py3.10-upgrade-dev:
        imageName: 'vs2017-win2016'
        pythonVersion: '3.10'
        testToxEnv: 'py310-upgrade-dev'
        buildToxEnv: 'build-py310-upgrade-dev'

      Windows-py3.10-upgrade-dev:
        imageName: 'vs2017-win2016'
        pythonVersion: '3.10'
        testToxEnv: 'py310-opt'
        buildToxEnv: 'build-py310-opt'

      Windows-py3.9:
        imageName: 'vs2017-win2016'
        pythonVersion: '3.9'
        testToxEnv: 'py39'
        buildToxEnv: 'build-py39'

      Windows-py3.8:
        imageName: 'vs2017-win2016'
        pythonVersion: '3.8'
        testToxEnv: 'py38'
        buildToxEnv: 'build-py38'

      Windows-py3.7:
        imageName: 'vs2017-win2016'
        pythonVersion: '3.7'
        testToxEnv: 'py37'
        buildToxEnv: 'build-py37'

      Windows-py3.7-min-req:
        imageName: 'vs2017-win2016'
        pythonVersion: '3.7'
        testToxEnv: 'py37-min-req'
        buildToxEnv: 'build-py37-min-req'

  pool:
    vmImage: $(imageName)

  steps:

  - checkout: self
    submodules: true

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(pythonVersion)'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip
      python -m pip install --upgrade setuptools
      python -m pip install wheel tox
    displayName: 'Install build dependencies'

  - bash: |
      tox -e $(testToxEnv)
    displayName: 'Run unit tests'

  - bash: |
      tox -e $(buildToxEnv)
    displayName: 'Build wheel and source distribution'

  - bash: |
      tox -e wheelinstall --recreate --installpkg dist/*-none-any.whl
    displayName: 'Test installation from a wheel'
