trigger:
- dev

jobs:

- job: 'Test'
  displayName: "Test HDMF"

  strategy:
    matrix:
      macOS-py3.10:
        imageName: 'macos-10.15'
        pythonVersion: '3.10'
        testToxEnv: 'py310'
        buildToxEnv: 'build-py310'

      macOS-py3.7-min-req:
        imageName: 'macos-10.15'
        pythonVersion: '3.7'
        testToxEnv: 'py37-min-req'
        buildToxEnv: 'build-py37-min-req'

      Windows-py3.10:
        imageName: 'vs2017-win2016'
        pythonVersion: '3.10'
        testToxEnv: 'py310'
        buildToxEnv: 'build-py310'

      Windows-py3.7-min-req:
        imageName: 'vs2017-win2016'
        pythonVersion: '3.7'
        testToxEnv: 'py37-min-req'
        buildToxEnv: 'build-py37-min-req'

  pool:
    vmImage: $(imageName)

  steps:
  - checkout: self
    submodules: true

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(pythonVersion)'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip
      python -m pip install --upgrade setuptools
      python -m pip install wheel tox
    displayName: 'Install build dependencies'

  - bash: |
      tox -e $(testToxEnv)
    displayName: 'Run unit tests'

  - bash: |
      tox -e $(buildToxEnv)
    displayName: 'Build wheel and source distribution'

  - bash: |
      tox -e wheelinstall --recreate --installpkg dist/*-none-any.whl
    displayName: 'Test installation from a wheel'
