name: Documentation
description: Is the documentation of something missing, unclear, or lacking? This is the place.
title: "[Documentation]: "
labels: "documentation"
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for your suggestion!

        We welcome any ideas about how to make **HDMF** better for the community.

        Please keep in mind that new or improved documentation may not get implemented immediately.
  - type: textarea
    id: summary
    attributes:
      label: What would you like changed or added to the documentation and why?
      description: Do you have any suggestions for the documents?
    validations:
      required: true
  - type: dropdown
    id: interest
    attributes:
      label: Do you have any interest in helping write or edit the documentation?
      description: |
        We appreciate any help you can offer!

        For information on how to contribute, please refer to our [contributing guidelines](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst).
      options:
        - Yes.
        - Yes, but I would need guidance.
        - No.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/hdmf-dev/hdmf/blob/dev/.github/CODE_OF_CONDUCT.md).

        Before submitting this issue, please review the [Contributing Guide](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst).

        Please also ensure that this issue has not already been [reported](https://github.com/hdmf-dev/hdmf/issues). Thank you!
