- data_type: VectorData
  namespace:
  namespace_version:
  fields:
    data: /Users/mavaylon/Research/NWB/hdmf2/hdmf/tests/unit/example_test_term_set.yaml
    field2: ...
# - data_type: #Container2
#   namespace:
#   namespace_version:
#   fields:
#     - name:
#       doc:
#       termset_path:
#     - name:
#       doc:
#       termset_path:
