name: Check Sphinx links
on:
  pull_request:
  schedule:
    - cron: '0 5 * * *'  # once per day at midnight ET
  workflow_dispatch:

jobs:
  check-sphinx-links:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0  # tags are required to determine the version

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # TODO update to 3.12 when optional reqs (e.g., oaklib) support 3.12

      - name: Install Sphinx dependencies and package
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-doc.txt -r requirements-opt.txt
          python -m pip install .

      - name: Check Sphinx internal and external links
        run: sphinx-build -W -b linkcheck ./docs/source ./test_build
