name: Codespell
on:
  push:
  workflow_dispatch:

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Codespell
        uses: codespell-project/actions-codespell@v2
