name: Deploy release
on:
  push:
    tags:  # run only on new tags that follow semver
      - '/^[0-9]+(\.[0-9]+)?(\.[0-9]+)?$/'

jobs:
  deploy-release:
    name: Deploy release from tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
          python -m pip list

      - name: Run tox tests
        run: |
          tox -e py310-upgraded

      - name: Build wheel and source distribution
        run: |
          tox -e build-py310-upgraded
          ls -1 dist

      - name: Test installation from a wheel
        run: |
          tox -e wheelinstall --recreate --installpkg dist/*-none-any.whl

      - name: Upload wheel and source distributions to PyPI  # TODO remove the --repository flag after testing
        run: |
          python -m pip install twine
          ls -1 dist
          twine upload --repository testpypi -u ${{ secrets.BOT_PYPI_USER }} -p ${{ secrets.BOT_PYPI_PASSWORD }} --skip-existing dist/*

      - name: Publish wheel and source distributions as a GitHub release
        run: |
          # use click<8 until https://github.com/j0057/github-release/issues/62 is resolved
          python -m pip install "click<8" githubrelease
          githubrelease release hdmf-dev/hdmf \
            create ${{ github.ref_name }} --name ${{ github.ref_name }} \
            --github-token ${{ secrets.BOT_GITHUB_TOKEN }} \
            --publish dist/*
