name: Deploy pre-release
on:
  push:
    branches:
    - dev
    tags:  # exclude tags created by "ci_addons publish_github_release"
    - '**'
    - '!latest'
    - '!latest-tmp'
jobs:
  deploy-dev:
    name: Deploy pre-release from dev
    runs-on: ubuntu-latest
    steps:
    - name: Cancel any previous incomplete runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}

    - name: Checkout repo with submodules
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Download wheel and source distributions from artifact
      uses: actions/download-artifact@v3
      with:
        name: distributions
        path: dist

    - name: Publish wheel and source distributions as a GitHub release
      run: |
        pip install --upgrade pip
        pip install scikit-ci-addons
        ci_addons publish_github_release hdmf-dev/hdmf  \
            --prerelease-packages "dist/*" \
            --prerelease-sha $GITHUB_SHA \
            --prerelease-packages-clear-pattern "*" \
            --prerelease-packages-keep-pattern "*dev<COMMIT_DISTANCE>*" \
            --re-upload
