name: Run PyNWB Unit, Integration, and Gallery Tests
on:
  pull_request:
  schedule:
    - cron: '0 5 * * *'  # once per day at midnight ET
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-pynwb-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false
          submodules: 'recursive'
          fetch-depth: 0  # tags are required to determine the version

      - name: Set up Python
        uses: actions/setup-python@v7.0.0
        with:
          python-version: '3.14'

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Clone PyNWB and install dev branch of HDMF
        run: |
          python -m pip list
          git clone https://github.com/NeurodataWithoutBorders/pynwb.git --recurse-submodules
          cd pynwb
          # install PyNWB with the test and docs dependency groups and the gallery extras; this will install a different version of hdmf from the current one
          python -m pip install --group test --group docs ".[zarr,termset]"
          cd ..
          python -m pip uninstall -y hdmf  # uninstall the other version of hdmf
          python -m pip install .  # reinstall current branch of hdmf
          python -m pip list

      - name: Run PyNWB tests on PyNWB dev branch
        run: |
          cd pynwb
          python test.py -v

      - name: Run PyNWB Gallery tests on PyNWB dev branch
        run: |
          cd pynwb
          python test.py -e -v
