name: Run HDMF-Zarr tests
on:
  pull_request:
  schedule:
    - cron: '0 5 * * *'  # once per day at midnight ET
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel non-latest runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0  # tags are required for versioneer to determine the version

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Clone HDMF-Zarr and install dev branch of HDMF
        run: |
          python -m pip list
          git clone https://github.com/hdmf-dev/hdmf-zarr.git --recurse-submodules
          cd hdmf-zarr
          python -m pip install -r requirements-dev.txt -r requirements.txt
          # must install in editable mode for coverage to find sources
          python -m pip install -e .  # this will install a pinned version of hdmf instead of the current one
          cd ..
          python -m pip uninstall -y hdmf  # uninstall the pinned version of hdmf
          python -m pip install .  # reinstall current branch of hdmf
          python -m pip list

      - name: Run HDMF-Zarr tests on HDMF-Zarr dev branch
        run: |
          cd hdmf-zarr
          pytest
