name: Run tests
on:
  pull_request:

jobs:
  run-tests-on-conda:
    name: conda-linux-python3.7-minimum
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0  # tags are required for versioneer to determine the version

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: true
          activate-environment: true
          python-version: "3.7"

      - name: Install build dependencies
        run: |
          conda config --set always_yes yes --set changeps1 no
          conda info
          conda install -c conda-forge tox
          conda list

      - name: Run tox tests
        run: |
          tox -e py37-minimum