name: Run all tests
on:
  schedule:
    - cron: '0 5 * * *'  # once per day at midnight ET
  push:
    tags:  # run only on new tags that follow semver
      - '/^[0-9]+(\.[0-9]+)?(\.[0-9]+)?$/'
  workflow_dispatch:

jobs:
  run-all-tests:
    # the only differences between this job and "run_tests.yml" is the "strategy.matrix.include" and the upload
    # distributions step.
    # GitHub Actions does not yet support YAML anchors, easily reusable components, or easy dynamic matrix
    # configurations based on the github event, so this job is duplicated for the most part
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.name }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: linux-python3.8-minimum       , test-tox-env: pytest-py38-minimum          , python-ver: "3.8" , os: ubuntu-latest }
          - { name: linux-python3.9               , test-tox-env: pytest-py39-pinned           , python-ver: "3.9" , os: ubuntu-latest }
          - { name: linux-python3.10              , test-tox-env: pytest-py310-pinned          , python-ver: "3.10", os: ubuntu-latest }
          - { name: linux-python3.11              , test-tox-env: pytest-py311-pinned          , python-ver: "3.11", os: ubuntu-latest }
          - { name: linux-python3.11-optional     , test-tox-env: pytest-py311-optional-pinned , python-ver: "3.11", os: ubuntu-latest }
          - { name: linux-python3.12              , test-tox-env: pytest-py312-pinned          , python-ver: "3.12", os: ubuntu-latest }
          - { name: linux-python3.12-upgraded     , test-tox-env: pytest-py312-upgraded        , python-ver: "3.12", os: ubuntu-latest }
          - { name: linux-python3.12-prerelease   , test-tox-env: pytest-py312-prerelease      , python-ver: "3.12", os: ubuntu-latest }
          - { name: windows-python3.8-minimum     , test-tox-env: pytest-py38-minimum          , python-ver: "3.8" , os: windows-latest }
          - { name: windows-python3.9             , test-tox-env: pytest-py39-pinned           , python-ver: "3.9" , os: windows-latest }
          - { name: windows-python3.10            , test-tox-env: pytest-py310-pinned          , python-ver: "3.10", os: windows-latest }
          - { name: windows-python3.11            , test-tox-env: pytest-py311-pinned          , python-ver: "3.11", os: windows-latest }
          - { name: windows-python3.11-optional   , test-tox-env: pytest-py311-optional-pinned , python-ver: "3.11", os: windows-latest }
          - { name: windows-python3.12            , test-tox-env: pytest-py312-pinned          , python-ver: "3.12", os: windows-latest }
          - { name: windows-python3.12-upgraded   , test-tox-env: pytest-py312-upgraded        , python-ver: "3.12", os: windows-latest }
          - { name: windows-python3.12-prerelease , test-tox-env: pytest-py312-prerelease      , python-ver: "3.12", os: windows-latest }
          - { name: macos-python3.8-minimum       , test-tox-env: pytest-py38-minimum          , python-ver: "3.8" , os: macos-latest }
          - { name: macos-python3.9               , test-tox-env: pytest-py39-pinned           , python-ver: "3.9" , os: macos-latest }
          - { name: macos-python3.10              , test-tox-env: pytest-py310-pinned          , python-ver: "3.10", os: macos-latest }
          - { name: macos-python3.11              , test-tox-env: pytest-py311-pinned          , python-ver: "3.11", os: macos-latest }
          - { name: macos-python3.11-optional     , test-tox-env: pytest-py311-optional-pinned , python-ver: "3.11", os: macos-latest }
          - { name: macos-python3.12              , test-tox-env: pytest-py312-pinned          , python-ver: "3.12", os: macos-latest }
          - { name: macos-python3.12-upgraded     , test-tox-env: pytest-py312-upgraded        , python-ver: "3.12", os: macos-latest }
          - { name: macos-python3.12-prerelease   , test-tox-env: pytest-py312-prerelease      , python-ver: "3.12", os: macos-latest }
    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0  # tags are required to determine the version

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-ver }}

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
          python -m pip list

      - name: Run tox tests
        run: |
          tox -e ${{ matrix.test-tox-env }}

      - name: Build wheel and source distribution
        run: |
          tox -e build
          ls -1 dist

      - name: Test installation from a wheel
        run: |
          tox -e wheelinstall --installpkg dist/*-none-any.whl

      - name: Test installation from a source distribution
        run: |
          tox -e wheelinstall --installpkg dist/*.tar.gz

  run-all-gallery-tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.name }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: linux-gallery-python3.8-minimum      , test-tox-env: gallery-py38-minimum          , python-ver: "3.8" , os: ubuntu-latest }
          - { name: linux-gallery-python3.11-optional    , test-tox-env: gallery-py311-optional-pinned , python-ver: "3.11", os: ubuntu-latest }
          - { name: linux-gallery-python3.12-upgraded    , test-tox-env: gallery-py312-upgraded        , python-ver: "3.12", os: ubuntu-latest }
          - { name: linux-gallery-python3.12-prerelease  , test-tox-env: gallery-py312-prerelease      , python-ver: "3.12", os: ubuntu-latest }
          - { name: windows-gallery-python3.8-minimum    , test-tox-env: gallery-py38-minimum          , python-ver: "3.8" , os: windows-latest }
          - { name: windows-gallery-python3.11-optional  , test-tox-env: gallery-py311-optional-pinned , python-ver: "3.11", os: windows-latest }
          - { name: windows-gallery-python3.12-upgraded  , test-tox-env: gallery-py312-upgraded        , python-ver: "3.12", os: windows-latest }
          - { name: windows-gallery-python3.12-prerelease, test-tox-env: gallery-py312-prerelease      , python-ver: "3.12", os: windows-latest }
          - { name: macos-gallery-python3.8-minimum      , test-tox-env: gallery-py38-minimum          , python-ver: "3.8" , os: macos-latest }
          - { name: macos-gallery-python3.11-optional    , test-tox-env: gallery-py311-optional-pinned , python-ver: "3.11", os: macos-latest }
          - { name: macos-gallery-python3.12-upgraded    , test-tox-env: gallery-py312-upgraded        , python-ver: "3.12", os: macos-latest }
          - { name: macos-gallery-python3.12-prerelease  , test-tox-env: gallery-py312-prerelease      , python-ver: "3.12", os: macos-latest }
    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0  # tags are required to determine the version

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-ver }}

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
          python -m pip list

      - name: Run tox tests
        run: |
          tox -e ${{ matrix.test-tox-env }}

  run-all-tests-on-conda:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    defaults:
     run:
       shell: bash -l {0}  # needed for conda environment to work
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.name }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: conda-linux-python3.8-minimum     , test-tox-env: pytest-py38-minimum          , python-ver: "3.8" , os: ubuntu-latest }
          - { name: conda-linux-python3.9             , test-tox-env: pytest-py39-pinned           , python-ver: "3.9" , os: ubuntu-latest }
          - { name: conda-linux-python3.10            , test-tox-env: pytest-py310-pinned          , python-ver: "3.10", os: ubuntu-latest }
          - { name: conda-linux-python3.11            , test-tox-env: pytest-py311-pinned          , python-ver: "3.11", os: ubuntu-latest }
          - { name: conda-linux-python3.11-optional   , test-tox-env: pytest-py311-optional-pinned , python-ver: "3.11", os: ubuntu-latest }
          - { name: conda-linux-python3.12            , test-tox-env: pytest-py312-pinned          , python-ver: "3.12", os: ubuntu-latest }
          - { name: conda-linux-python3.12-upgraded   , test-tox-env: pytest-py312-upgraded        , python-ver: "3.12", os: ubuntu-latest }
          - { name: conda-linux-python3.12-prerelease , test-tox-env: pytest-py312-prerelease      , python-ver: "3.12", os: ubuntu-latest }
    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0  # tags are required to determine the version

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-ver }}

      - name: Install build dependencies
        run: |
          conda config --set always_yes yes --set changeps1 no
          conda info
          conda install -c conda-forge "tox>=4"

      - name: Conda reporting
        run: |
          conda info
          conda config --show-sources
          conda list --show-channel-urls

      - name: Run tox tests
        run: |
          tox -e ${{ matrix.test-tox-env }}

      - name: Build wheel and source distribution
        run: |
          tox -e build
          ls -1 dist

      - name: Test installation from a wheel
        run: |
          tox -e wheelinstall --installpkg dist/*-none-any.whl

      - name: Test installation from a source distribution
        run: |
          tox -e wheelinstall --installpkg dist/*.tar.gz

  run-gallery-ros3-tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}  # necessary for conda
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.name }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: linux-gallery-python3.12-ros3   , python-ver: "3.12", os: ubuntu-latest }
          - { name: windows-gallery-python3.12-ros3 , python-ver: "3.12", os: windows-latest }
          - { name: macos-gallery-python3.12-ros3   , python-ver: "3.12", os: macos-latest }
    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0  # tags are required to determine the version

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: ros3
          environment-file: environment-ros3.yml
          python-version: ${{ matrix.python-ver }}
          channels: conda-forge
          auto-activate-base: false

      - name: Install run dependencies
        run: |
          pip install -e .
          pip list

      - name: Conda reporting
        run: |
          conda info
          conda config --show-sources
          conda list --show-channel-urls

      - name: Run ros3 tests  # TODO include gallery tests after they are written
        run: |
          pytest tests/unit/test_io_hdf5_streaming.py
