name: Run HDMF-Zarr tests
on:
  pull_request:
  schedule:
    - cron: '0 5 * * *'  # once per day at midnight ET
  workflow_dispatch:

jobs:
  run-hdmf-zarr-tests:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0  # tags are required to determine the version

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Clone HDMF-Zarr and install dev branch of HDMF
        run: |
          python -m pip list
          git clone https://github.com/hdmf-dev/hdmf-zarr.git --recurse-submodules
          cd hdmf-zarr
          python -m pip install -r requirements-dev.txt -r requirements.txt
          # must install in editable mode for coverage to find sources
          python -m pip install -e .  # this will install a pinned version of hdmf instead of the current one
          cd ..
          python -m pip uninstall -y hdmf  # uninstall the pinned version of hdmf
          python -m pip install .  # reinstall current branch of hdmf
          python -m pip list

      - name: Run HDMF-Zarr tests on HDMF-Zarr dev branch
        run: |
          cd hdmf-zarr
          pytest
