name: Run tests
on:
  push:
    branches:
    - '**'
    tags:
    - '**'
    - '!latest'
    - '!latest-tmp'
  pull_request:
    branches:
    - '**'
jobs:
  run-tests:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        include:
          - name: "python3.7-min-req"
            test-tox-env: "py37-min-req"
            build-tox-env: "build-py37-min-req"
            python-ver: "3.7"
          - name: "python3.7"
            test-tox-env: "py37"
            build-tox-env: "build-py37"
            python-ver: "3.7"
          - name: "python3.8"
            test-tox-env: "py38"
            build-tox-env: "build-py38"
            python-ver: "3.8"
          - name: "python3.9"
            test-tox-env: "py39"
            build-tox-env: "build-py39"
            python-ver: "3.9"
          - name: "python3.10"
            test-tox-env: "py310"
            build-tox-env: "build-py310"
            python-ver: "3.10"
          - name: "python3.10-opt"
            test-tox-env: "py310-opt"
            build-tox-env: "build-py310-opt"
            python-ver: "3.10"
          - name: "python3.10-upgrade-dev"
            test-tox-env: "py310-upgrade-dev"
            build-tox-env: "build-py310-upgrade-dev"
            python-ver: "3.10"
          - name: "python3.10-upgrade-dev-pre"
            test-tox-env: "py310-upgrade-dev-pre"
            build-tox-env: "build-py310-upgrade-dev-pre"
            python-ver: "3.10"
          - name: "miniconda3.7"
            test-tox-env: "py37"
            build-tox-env: "build-py37"
            conda-python-ver: "3.7"
          - name: "miniconda3.8"
            test-tox-env: "py38"
            build-tox-env: "build-py38"
            conda-python-ver: "3.8"
          - name: "miniconda3.9"
            test-tox-env: "py39"
            build-tox-env: "build-py39"
            conda-python-ver: "3.9"
          - name: "miniconda3.10"
            test-tox-env: "py310"
            build-tox-env: "build-py310"
            conda-python-ver: "3.10"
    steps:
    - name: Cancel any previous incomplete runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Set up Python
      uses: actions/setup-python@v3
      if: ${{ matrix.python-ver }}
      with:
        python-version: ${{ matrix.python-ver }}
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      if: ${{ matrix.conda-python-ver }}
      with:
        auto-update-conda: true
        auto-activate-base: true
        activate-environment: ""
    - name: Install build dependencies
      if: ${{ matrix.python-ver }}
      run: |
        # Installing HDF5 is required for building h5py 2.10 wheels for Python 3.9+
        if [[ "${{ matrix.test-tox-env }}" == *"py39"* ]] || [[ "${{ matrix.test-tox-env }}" == *"py310"* ]]; then
          sudo apt-get install libhdf5-dev
        fi
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools
        python -m pip install wheel tox
    - name: Install build dependencies (conda)
      if: ${{ matrix.conda-python-ver }}
      run: |
        conda update -n base -c defaults conda
        conda config --set always_yes yes --set changeps1 no
        conda config --add channels conda-forge
        conda install python=${{ matrix.conda-python-ver }}
        # work around incompatibilities between virtualenv & importlib-metadata
        if [[ "${{ matrix.test-tox-env }}" == *"py37"* ]]; then
          conda install "importlib-metadata=1.7"
        else
          conda install importlib-metadata
        fi
        conda install tox
    - name: Run unit tests
      run: |
        tox -e ${{ matrix.test-tox-env }}
    - name: Build wheel and source distribution
      run: |
        tox -e ${{ matrix.build-tox-env }}
    - name: Test installation from a wheel
      run: |
        tox -e wheelinstall --recreate --installpkg dist/*-none-any.whl
