name: Testing External Links
on: pull_request
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel any previous incomplete runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install Sphinx dependencies
      run: pip install -r requirements-doc.txt
    - name: Test external links
      run: sphinx-build -b linkcheck ./docs/source ./test_build
