name: Run PyNWB tests
on: pull_request
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel any previous incomplete runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Update pip
      run: python -m pip install --upgrade pip
    - name: Run
      run: |
        pip list
        git clone https://github.com/NeurodataWithoutBorders/pynwb.git --recurse-submodules
        cd pynwb
        pip install -U -rrequirements-dev.txt -rrequirements.txt
        pip install -e .  # this will install a particular version of hdmf instead of the current one
        cd ..
        pip uninstall -y hdmf
        pip install -e .  # reinstall current branch of hdmf
        pip list
        pip check
    - name: Run PyNWB tests
      run: |
        cd pynwb
        python test.py -v
